### ISSUE TITLE
Microsite could not find datasets when Rudolf API defined on settings

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/microsite#5]
Hi @pierorex 

I have set up microsite locally and changed the default settings in settings.py as follows
```
OS_VIEWER_THEMES_FOLDER = 'os_viewer_themes'
OS_VIEWER_HOST = 'http://apps.openbudgets.eu/viewer'
OS_API = 'http://apps.openbudgets.eu/api/3/cubes'
```
I manage to login in microsite backend but when try to add a new dataset, the autocomplete will not return any dataset for the term ```thessaloniki```, whilst there definetely is at least one as can be seen [here](http://apps.openbudgets.eu/api/3/cubes)

I get the following error message on the console
```
[05/Aug/2017 08:39:53] "GET /vizmanager/dataset-autocomplete/?q=Thessalon HTTP/1.1" 500 17720
Internal Server Error: /vizmanager/dataset-autocomplete/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dal/views.py", line 48, in dispatch
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sotos/PycharmProjects/microsite/vizmanager/views.py", line 48, in get
    for dataset in r.json():
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

If I change back to the default settings, it seems to find only one dataset and only if I enter the whole word "thessaloniki" but perhaps this is another issue.

**Comment by skarampatakis** [comment]
It seems that the OS_API was set wrong. I changed to 
```
OS_API = 'http://apps.openbudgets.eu/api/3
```
And seems to be working. 

However, datasets that was already stored on the database are not rendered correctly. I think they should be removed.

**Comment by pierorex** [comment]
Thank you for checking the app @skarampatakis :)
